#!/usr/bin/bash

network_interface="enp0s31f6"

nmcli_output=$(nmcli connection show | grep "$network_interface")
connection_state=$(ip addr show | grep "$network_interface:" | awk '{print $9}')
connection_name=$(echo $nmcli_output | awk '{print $1}')
connection_type=$(echo $nmcli_output | awk '{print $3}')

if [ $1 == "state" ]; then
  echo "$connection_state"
elif [ $1 == "name" ]; then
  echo "$connection_name"
elif [ $1 == "type" ]; then
  echo "$connection_type"
fi