#!/usr/bin/python

import os, imaplib

user = os.getenv("GMAIL_USER")
password = os.getenv("GMAIL_PASSWORD")

obj = imaplib.IMAP4_SSL("imap.gmail.com", "993")
obj.login(user, password)
obj.select()

print(len(obj.search(None, "UnSeen")[1][0].split()))
